# Generated by Django 4.2.15 on 2024-09-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomrates', '0003_rename_room_id_roomrate_room_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomrate',
            old_name='room_ids',
            new_name='room_id',
        ),
    ]
